# CallQTV Source Code Documentation

## Project Overview
CallQTV is a next-generation Android Television and IoT queue display system. It provides a real-time, responsive interface for tracking token numbers across multiple counters, alongside dynamic advertisement delivery. Built with **MVVM**, **Kotlin Coroutines**, and **Jetpack Compose**, it is optimized for stability and visual excellence.

---

## 🏗️ Architecture (MVVM)

The project follows a modular MVVM architecture to ensure high maintainability:

- **View Layer (`ui`)**: 100% Jetpack Compose. Handles layout adaptation and user interactions.
- **ViewModel Layer (`viewmodel`)**: Manages UI state, MQTT data streams, and registration logic.
- **Data Layer (`data`)**:
    - **Local**: Room Database for offline-first resilience.
    - **Network**: Retrofit for RESTful config and registration APIs.
    - **Repository**: Single source of truth for UI data.
- **Support Layer (`utils`)**: Contains the AI Semantic Parser, Voice Announcer, and Theme Managers.

---

## 🌟 Premium Features

### 1. Responsive Layout Engine 📱📺
The UI is built with a custom **Dynamic Scaling Engine**.
- **Orientation Awareness**: Automatically switches between `Row` (Landscape/TV) and `Column` (Mobile/Portrait) layouts.
- **Density-Independent Scaling**: All visual elements (text, cards, padding) scale proportionally to the screen size based on a 1920dp baseline.
- **Glassmorphic UI**: Uses modern gradients and smooth transitions to provide a premium feel.

### 2. Intelligent Message Parsing (AI & Semantic) 🧠
The app features a advanced `SemanticMqttParser` that understands varied message formats:
- **Hardware Protocol**: Recognizes fixed-length industrial packets (e.g., `$0202505CAL000006403660*`) to extract Serial, Counter ID, and Token values.
- **AI/NLP Parsing**: Leverages a semantic engine to "understand" natural language messages (e.g., "Calling token 501 to Counter A").
- **Digit Normalization**: Automatically strips padding (e.g., `036` → `36`) for a cleaner display.

### 3. Smart Voice Announcement 🎙️
The `TokenAnnouncer` provides high-quality audio guidance:
- **Phonetic Expansion**: Tokens are expanded digit-by-digit (e.g., "101" becomes "one zero one") to ensure clarity and prevent engines from grouping numbers into "hundreds" or "thousands".
- **Contextual Phrases**: Automatically constructs phrases like *"Token number 50, please proceed to Reception"*.
- **Offline Resilience**: Works across various Android devices including those without Google Play Services (GMS).
- **Silent Heartbeat**: Periodically "tickles" the TTS engine to prevent it from being suspended by the OS during idle periods.

### 4. Multi-BLUCON Connectivity 🔌
Unlike standard apps, CallQTV can connect to **multiple MQTT brokers** simultaneously.
- Maintains independent connection pools via a Uri-mapped `MqttClientManager` system.
- Shared state updates: All tokens from different brokers are unified into a single UI view.
- Persistent Subscriptions: Automatically re-subscribes to topics after network restoration using `MqttCallbackExtended`.

---

## 🛠️ Technical Stack

- **Language**: Kotlin 1.9.25
- **UI**: Jetpack Compose (BOM 2024.08)
- **Networking**: Retrofit 2.11 + OkHttp 4.12
- **Persistence**: Room 2.6.1 (SQL-based config cache)
- **Messaging**: Paho MQTT v3
- **Image/Media**: Coil for high-performance ad loading.
- **AI/ML**: ML Kit Entity Extraction for semantic understanding.

---

## 🚀 Key Flow: Device Registration
1. **Product Auth**: Validates the Mac Address and Customer ID.
2. **Device Registration**: Registers the TV/Phone with the central dashboard.
3. **Status Check**: Checks for license expiry and software updates.
4. **Config Sync**: Downloads and caches the personalized display settings.

---

Documentation generated by **Antigravity AI**.  
*Ensuring your Queue Management is as smart as your hardware.*
